name: 'Find changed submodules'
description: 'Find out which submodule has changed'
outputs:
  repo_url:
    description: "URL of the changed submodule"
    value: ${{ steps.git-log.outputs.repo_url }}
  repo_commit:
    description: "Commit of the changed submodule"
    value: ${{ steps.git-log.outputs.repo_commit }}
runs:
  using: "composite"
  steps: 
    - id: git-log
      shell: bash
      run: |
        PKG=$(git log --pretty=format: --name-only HEAD^.. | grep "^[^.]")
        echo "New package: ${PKG}"
        git submodule init ${PKG}
        REPO_URL=$(git config --list | grep "submodule.${PKG}.url=" | cut -d'=' -f2)
        REPO_COMMIT=$(git submodule status $PKG | awk '{print $1}' | sed 's/^[^0-9a-z]*//')
        echo ::set-output name=repo_url::$REPO_URL
        echo ::set-output name=repo_commit::$REPO_COMMIT
